import p50_img from "../../assets/img-scarpe/product_50.png";
import p51_img from "../../assets/img-scarpe/product_51.png";
import p52_img from "../../assets/img-scarpe/product_52.png";
import p53_img from "../../assets/img-scarpe/product_53.png";
import p54_img from "../../assets/img-scarpe/product_54.png";
import p55_img from "../../assets/img-scarpe/product_55.png";
import p56_img from "../../assets/img-scarpe/product_56.png";
import p57_img from "../../assets/img-scarpe/product_57.png";
import p58_img from "../../assets/img-scarpe/product_58.png";
import p59_img from "../../assets/img-scarpe/product_59.png";
import p60_img from "../../assets/img-scarpe/product_60.png";
import p61_img from "../../assets/img-scarpe/product_61.png";
import p62_img from "../../assets/img-scarpe/product_62.png";
import p63_img from "../../assets/img-scarpe/product_63.png";
import p64_img from "../../assets/img-scarpe/product_64.png";
import p65_img from "../../assets/img-scarpe/product_65.png";
import p66_img from "../../assets/img-scarpe/product_66.png";
import p67_img from "../../assets/img-scarpe/product_67.png";
import p68_img from "../../assets/img-scarpe/product_68.png";
import p69_img from "../../assets/img-scarpe/product_69.png";
import p70_img from "../../assets/img-scarpe/product_70.png";
import p71_img from "../../assets/img-scarpe/product_71.png";
import p72_img from "../../assets/img-scarpe/product_72.png";
import p73_img from "../../assets/img-scarpe/product_73.png";
import p74_img from "../../assets/img-scarpe/product_74.png";
import p75_img from "../../assets/img-scarpe/product_75.png";
import p76_img from "../../assets/img-scarpe/product_76.png";
import p77_img from "../../assets/img-scarpe/product_77.png";
import p78_img from "../../assets/img-scarpe/product_78.png";
import p79_img from "../../assets/img-scarpe/product_79.png";
import p80_img from "../../assets/img-scarpe/product_80.png";
import p81_img from "../../assets/img-scarpe/product_81.png";
import p82_img from "../../assets/img-scarpe/product_82.png";
import p83_img from "../../assets/img-scarpe/product_83.png";
import p84_img from "../../assets/img-scarpe/product_84.png";
import p85_img from "../../assets/img-scarpe/product_85.png";
import p86_img from "../../assets/img-scarpe/product_86.png";
import p87_img from "../../assets/img-scarpe/product_87.png";
import p88_img from "../../assets/img-scarpe/product_88.png";
import p89_img from "../../assets/img-scarpe/product_89.png";
import p90_img from "../../assets/img-scarpe/product_90.png";
import p91_img from "../../assets/img-scarpe/product_91.png";

import p1_img from "../../assets/img-donna/product_1.png";
import p2_img from "../../assets/img-donna/product_2.png";
import p3_img from "../../assets/img-donna/product_3.png";
import p4_img from "../../assets/img-donna/product_4.png";
import p5_img from "../../assets/img-donna/product_5.png";
import p6_img from "../../assets/img-donna/product_6.png";
import p7_img from "../../assets/img-donna/product_7.png";
import p8_img from "../../assets/img-donna/product_8.png";
import p9_img from "../../assets/img-donna/product_9.png";
import p10_img from "../../assets/img-donna/product_10.png";
import p11_img from "../../assets/img-donna/product_11.png";
import p12_img from "../../assets/img-donna/product_12.png";
import p13_img from "../../assets/img-donna/product_13.png";
import p14_img from "../../assets/img-donna/product_14.png";
import p15_img from "../../assets/img-donna/product_15.png";
import p16_img from "../../assets/img-donna/product_16.png";
import p17_img from "../../assets/img-donna/product_17.png";
import p18_img from "../../assets/img-donna/product_18.png";
import p19_img from "../../assets/img-donna/product_19.png";
import p20_img from "../../assets/img-donna/product_20.png";
import p21_img from "../../assets/img-donna/product_21.png";
import p22_img from "../../assets/img-donna/product_22.png";
import p23_img from "../../assets/img-donna/product_23.png";
import p24_img from "../../assets/img-donna/product_24.png";
import p25_img from "../../assets/img-donna/product_25.png";
import p206_img from "../../assets/img-donna/product_206.png";
import p207_img from "../../assets/img-donna/product_207.png";

//Uomo
import p26_img from "../../assets/img-uomo/product_26.png";
import p27_img from "../../assets/img-uomo/product_27.png";
import p28_img from "../../assets/img-uomo/product_28.png";
import p29_img from "../../assets/img-uomo/product_29.png";
import p30_img from "../../assets/img-uomo/product_30.png";
import p31_img from "../../assets/img-uomo/product_31.png";
import p32_img from "../../assets/img-uomo/product_32.png";
import p33_img from "../../assets/img-uomo/product_33.png";
import p34_img from "../../assets/img-uomo/product_34.png";
import p35_img from "../../assets/img-uomo/product_35.png";
import p36_img from "../../assets/img-uomo/product_36.png";
import p37_img from "../../assets/img-uomo/product_37.png";
import p38_img from "../../assets/img-uomo/product_38.png";
import p39_img from "../../assets/img-uomo/product_39.png";
import p40_img from "../../assets/img-uomo/product_40.png";
import p41_img from "../../assets/img-uomo/product_41.png";
import p42_img from "../../assets/img-uomo/product_42.png";
import p43_img from "../../assets/img-uomo/product_43.png";
import p44_img from "../../assets/img-uomo/product_44.png";
import p45_img from "../../assets/img-uomo/product_45.png";
import p46_img from "../../assets/img-uomo/product_46.png";
import p47_img from "../../assets/img-uomo/product_47.png";
import p48_img from "../../assets/img-uomo/product_48.png";
import p49_img from "../../assets/img-uomo/product_49.png";
import p501_img from "../../assets/img-uomo/product_501.png";
import p502_img from "../../assets/img-uomo/product_502.png";

const all = [
  {
    id: 50,
    img: p50_img,
    title: "SCARPE",
    prevPrice: "120",
    newPrice: "99.99",
    brand: "Nike",
    color: "white",
    category: "lifestyle",
    gender: "uomo",
    price: 99.99,
  },
  {
    id: 51,
    img: p51_img,
    title: "Nike Air Vapormax Plus",
    prevPrice: "100",
    newPrice: "88.99",
    brand: "Nike",
    color: "white",
    category: "lifestyle",
    gender: "uomo",
    price: 88.99,
  },

  {
    id: 52,
    img: p52_img,
    title: "Nike Waffle One Sneaker",
    prevPrice: "110",
    newPrice: "95.99",
    brand: "Nike",
    color: "green",
    category: "lifestyle",
    gender: "uomo",
    price: 95.99,
  },
  {
    id: 53,
    img: p53_img,
    title: "Nike Running Shoe",
    prevPrice: "130",
    newPrice: "110.99",
    brand: "Adidas",
    color: "black",
    category: "lifestyle",
    gender: "uomo",
    price: 110.99,
  },
  {
    id: 54,
    img: p54_img,
    title: "Flat Slip On Pumps",
    prevPrice: "140",
    newPrice: "120.99",
    brand: "Vans",
    color: "green",
    category: "tennis",
    gender: "uomo",
    price: 120.99,
  },
  {
    id: 55,
    img: p55_img,
    title: "Knit Ballet Flat",
    prevPrice: "150",
    newPrice: "130,99",
    brand: "Adidas",
    color: "black",
    category: "tennis",
    gender: "uomo",
    price: 130.99,
  },
  {
    id: 56,
    img: p56_img,
    title: "Flat Slip On Pumps",
    prevPrice: "165",
    newPrice: "150.99",
    brand: "Vans",
    color: "green",
    category: "tennis",
    gender: "uomo",
    price: 150.99,
  },
  {
    id: 57,
    img: p57_img,
    title: "Knit Ballet Flat",
    prevPrice: "140",
    newPrice: "115,99",
    brand: "Adidas",
    color: "black",
    category: "tennis",
    gender: "uomo",
    price: 115.99,
  },
  {
    id: 58,
    img: p58_img,
    title: "Flat Slip On Pumps",
    prevPrice: "130",
    newPrice: "105.99",
    brand: "Vans",
    color: "green",
    category: "running",
    gender: "uomo",
    price: 105.99,
  },
  {
    id: 59,
    img: p59_img,
    title: "Knit Ballet Flat",
    prevPrice: "180",
    newPrice: "160,99",
    brand: "Adidas",
    color: "black",
    category: "running",
    gender: "uomo",
    price: 160.99,
  },
  {
    id: 60,
    img: p60_img,
    title: "Flat Slip On Pumps",
    prevPrice: "130",
    newPrice: "109.99",
    brand: "Vans",
    color: "green",
    category: "running",
    gender: "uomo",
    price: 109.99,
  },
  {
    id: 61,
    img: p61_img,
    title: "Knit Ballet Flat",
    prevPrice: "220",
    newPrice: "199,99",
    brand: "Adidas",
    color: "black",
    category: "running",
    gender: "uomo",
    price: 199.99,
  },
  {
    id: 62,
    img: p62_img,
    title: "Flat Slip On Pumps",
    prevPrice: "200",
    newPrice: "180.99",
    brand: "Vans",
    color: "green",
    category: "calcio",
    gender: "uomo",
    price: 180.99,
  },
  {
    id: 63,
    img: p63_img,
    title: "Knit Ballet Flat",
    prevPrice: "179",
    newPrice: "149,99",
    brand: "Adidas",
    color: "black",
    category: "calcio",
    gender: "uomo",
    price: 149.99,
  },
  {
    id: 64,
    img: p64_img,
    title: "Flat Slip On Pumps",
    prevPrice: "100",
    newPrice: "99.99",
    brand: "Vans",
    color: "green",
    category: "calcio",
    gender: "uomo",
    price: 99.99,
  },
  {
    id: 65,
    img: p65_img,
    title: "Knit Ballet Flat",
    prevPrice: "140",
    newPrice: "132,99",
    brand: "Adidas",
    color: "black",
    category: "calcio",
    gender: "uomo",
    price: 132.99,
  },
  {
    id: 66,
    img: p66_img,
    title: "Knit Ballet Flat",
    prevPrice: "150",
    newPrice: "109,99",
    brand: "Adidas",
    color: "black",
    category: "lifestyle",
    gender: "donna",
    price: 109.99,
  },
  {
    id: 67,
    img: p67_img,
    title: "Knit Ballet Flat",
    prevPrice: "210",
    newPrice: "189,99",
    brand: "Adidas",
    color: "black",
    category: "lifestyle",
    gender: "donna",
    price: 189.99,
  },
  {
    id: 68,
    img: p68_img,
    title: "Knit Ballet Flat",
    prevPrice: "170",
    newPrice: "149,99",
    brand: "Adidas",
    color: "black",
    category: "lifestyle",
    gender: "donna",
    price: 149.99,
  },
  {
    id: 69,
    img: p69_img,
    title: "Knit Ballet Flat",
    prevPrice: "230",
    newPrice: "209,99",
    brand: "Adidas",
    color: "black",
    category: "lifestyle",
    gender: "donna",
    price: 209.99,
  },
  {
    id: 70,
    img: p70_img,
    title: "Knit Ballet Flat",
    prevPrice: "180",
    newPrice: "169,99",
    brand: "Adidas",
    color: "black",
    category: "tennis",
    gender: "donna",
    price: 169.99,
  },
  {
    id: 71,
    img: p71_img,
    title: "Knit Ballet Flat",
    prevPrice: "180",
    newPrice: "169,99",
    brand: "Adidas",
    color: "black",
    category: "tennis",
    gender: "donna",
    price: 169.99,
  },
  {
    id: 72,
    img: p72_img,
    title: "Knit Ballet Flat",
    prevPrice: "250",
    newPrice: "209,99",
    brand: "Adidas",
    color: "black",
    category: "tennis",
    gender: "donna",
    price: 209.99,
  },
  {
    id: 73,
    img: p73_img,
    title: "Knit Ballet Flat",
    prevPrice: "130",
    newPrice: "99,99",
    brand: "Adidas",
    color: "black",
    category: "tennis",
    gender: "donna",
    price: 99.99,
  },
  {
    id: 74,
    img: p74_img,
    title: "Knit Ballet Flat",
    prevPrice: "100",
    newPrice: "84,99",
    brand: "Adidas",
    color: "black",
    category: "running",
    gender: "donna",
    price: 84.99,
  },
  {
    id: 75,
    img: p75_img,
    title: "Knit Ballet Flat",
    prevPrice: "89",
    newPrice: "75,99",
    brand: "Adidas",
    color: "black",
    category: "running",
    gender: "donna",
    price: 75.99,
  },
  {
    id: 76,
    img: p76_img,
    title: "Knit Ballet Flat",
    prevPrice: "90",
    newPrice: "73,99",
    brand: "Adidas",
    color: "black",
    category: "running",
    gender: "donna",
    price: 73.99,
  },
  {
    id: 77,
    img: p77_img,
    title: "Knit Ballet Flat",
    prevPrice: "100",
    newPrice: "80,99",
    brand: "Adidas",
    color: "black",
    category: "running",
    gender: "donna",
    price: 80.99,
  },
  {
    id: 78,
    img: p78_img,
    title: "Knit Ballet Flat",
    prevPrice: "190",
    newPrice: "159,99",
    brand: "Adidas",
    color: "black",
    category: "calcio",
    gender: "donna",
    price: 159.99,
  },
  {
    id: 79,
    img: p79_img,
    title: "Knit Ballet Flat",
    prevPrice: "200",
    newPrice: "179,99",
    brand: "Adidas",
    color: "black",
    category: "calcio",
    gender: "donna",
    price: 179.99,
  },
  {
    id: 80,
    img: p80_img,
    title: "Knit Ballet Flat",
    prevPrice: "220",
    newPrice: "189,99",
    brand: "Adidas",
    color: "black",
    category: "calcio",
    gender: "donna",
    price: 189.99,
  },
  {
    id: 81,
    img: p81_img,
    title: "Knit Ballet Flat",
    prevPrice: "200",
    newPrice: "149,99",
    brand: "Adidas",
    color: "black",
    category: "calcio",
    gender: "donna",
    price: 149.99,
  },
  {
    id: 82,
    img: p82_img,
    title: "Knit Ballet Flat",
    prevPrice: "70",
    newPrice: "49,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 49.99,
  },
  {
    id: 83,
    img: p83_img,
    title: "Knit Ballet Flat",
    prevPrice: "70",
    newPrice: "49,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 49.99,
  },
  {
    id: 84,
    img: p84_img,
    title: "Knit Ballet Flat",
    prevPrice: "80",
    newPrice: "42,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 42.99,
  },
  {
    id: 85,
    img: p85_img,
    title: "Knit Ballet Flat",
    prevPrice: "100",
    newPrice: "85,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 85.99,
  },
  {
    id: 86,
    img: p86_img,
    title: "Knit Ballet Flat",
    prevPrice: "100",
    newPrice: "70,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 70.99,
  },
  {
    id: 87,
    img: p87_img,
    title: "Knit Ballet Flat",
    prevPrice: "55",
    newPrice: "42,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 42,
  },
  {
    id: 88,
    img: p88_img,
    title: "Knit Ballet Flat",
    prevPrice: "80",
    newPrice: "55,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 55.99,
  },
  {
    id: 89,
    img: p89_img,
    title: "Knit Ballet Flat",
    prevPrice: "77",
    newPrice: "63,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 63.99,
  },
  {
    id: 90,
    img: p90_img,
    title: "Knit Ballet Flat",
    prevPrice: "89",
    newPrice: "63,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 63.99,
  },
  {
    id: 91,
    img: p91_img,
    title: "Knit Ballet Flat",
    prevPrice: "89",
    newPrice: "61,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 61.99,
  },
  {
    id: 1,
    img: p1_img,
    title: "EXCLUSIVE V NECK MINI DRESS",
    prevPrice: "54",
    newPrice: "34,99",
    brand: "altri marchi",
    color: "black",
    category: "vestiti",
    price: 34,
  },
  {
    id: 2,
    img: p2_img,
    title: "CLOCKHOUSE",
    prevPrice: "70",
    newPrice: "49,99",
    brand: "altri marchi",
    color: "grey",
    category: "vestiti",
    price: 49,
  },

  {
    id: 3,
    img: p3_img,
    title: "SQUARE NECK MINI",
    prevPrice: "90",
    newPrice: "69,99",
    brand: "altri marchi",
    color: "white",
    category: "vestiti",
    price: 69,
  },
  {
    id: 4,
    img: p4_img,
    title: "RUDINA",
    prevPrice: "140",
    newPrice: "119,99",
    brand: "stradivarius",
    color: "black",
    category: "t-shirt e top",
    price: 119,
  },
  {
    id: 5,
    img: p5_img,
    title: "COWL NECK TOPs",
    prevPrice: "85",
    newPrice: "62,99",
    brand: "even&odd",
    color: "black",
    category: "t-shirt e top",
    price: 62,
  },
  {
    id: 6,
    img: p6_img,
    title: "SEAMLESS TEXTURED",
    prevPrice: "45",
    newPrice: "29,99",
    brand: "stradivarius",
    color: "white",
    category: "t-shirt e top",
    price: 29,
  },
  {
    id: 7,
    img: p7_img,
    title: "Stretch bell bottom trousers",
    prevPrice: "100",
    newPrice: "79,99",
    brand: "pull&bear",
    color: "black",
    category: "pantaloni",
    price: 79,
  },
  {
    id: 8,
    img: p8_img,
    title: "SPACER JOGGERS",
    prevPrice: "59",
    newPrice: "39,99",
    brand: "calvin klein",
    color: "black",
    category: "pantaloni",
    price: 39,
  },

  {
    id: 9,
    img: p9_img,
    title: "STRAIGHT FIT",
    prevPrice: "40",
    newPrice: "33,99",
    brand: "bershka",
    color: "blue",
    category: "pantaloni",
    price: 33,
  },
  {
    id: 10,
    img: p10_img,
    title: "WITH CROSSOVER WAISTBAND",
    prevPrice: "69",
    newPrice: "40,99",
    brand: "pull&bear",
    color: "blue",
    category: "jeans",
    price: 40,
  },
  {
    id: 11,
    img: p11_img,
    title: "VINTAGE WITH RIPS",
    prevPrice: "55",
    newPrice: "39,99",
    brand: "bershka",
    color: "blue",
    category: "jeans",
    price: 39,
  },
  {
    id: 12,
    img: p12_img,
    title: "501® ORIGINAL",
    prevPrice: "110",
    newPrice: "89,99",
    brand: "levi's",
    color: "blue",
    category: "jeans",
    price: 89,
  },
  {
    id: 13,
    img: p13_img,
    title: "Smanicato",
    prevPrice: "100",
    newPrice: "74,99",
    brand: "bershka",
    color: "black",
    category: "giacche",
    price: 74,
  },
  {
    id: 14,
    img: p14_img,
    title: "501® ORIGINAL",
    prevPrice: "200",
    newPrice: "169,99",
    brand: "levi's",
    color: "pink",
    category: "giacche",
    price: 169,
  },

  {
    id: 15,
    img: p15_img,
    title: "JACKET 2000",
    prevPrice: "180",
    newPrice: "139,99",
    brand: "the north face",
    color: "violet",
    category: "giacche",
    price: 139,
  },
  {
    id: 16,
    img: p16_img,
    title: "SIDE TIE CHEEKY",
    prevPrice: "70",
    newPrice: "59,99",
    brand: "tommy hilfiger",
    color: "red",
    category: "moda mare",
    price: 59,
  },
  {
    id: 17,
    img: p17_img,
    title: "ISLAND SONG HIKE-DA",
    prevPrice: "79",
    newPrice: "69,99",
    brand: "altri marchi",
    color: "pink",
    category: "moda mare",
    price: 69,
  },
  {
    id: 18,
    img: p18_img,
    title: "Bikini pezzo sotto",
    prevPrice: "60",
    newPrice: "49,99",
    brand: "altri marchi",
    color: "black",
    category: "moda mare",
    price: 49,
  },
  {
    id: 19,
    img: p19_img,
    title: "GONNA - Minigonna",
    prevPrice: "55",
    newPrice: "42,99",
    brand: "tommy hilfiger",
    color: "pink",
    category: "gonne",
    price: 42,
  },
  {
    id: 20,
    img: p20_img,
    title: "Gonna a campana",
    prevPrice: "40",
    newPrice: "33,99",
    brand: "altri marchi",
    color: "blue",
    category: "gonne",
    price: 33,
  },

  {
    id: 21,
    img: p21_img,
    title: "SANTOS MINI X KRISTINA",
    prevPrice: "89",
    newPrice: "70,99",
    brand: "altri marchi",
    color: "pink",
    category: "gonne",
    price: 70,
  },
  {
    id: 22,
    img: p22_img,
    title: "Tuta jumpsuit",
    prevPrice: "100",
    newPrice: "79,99",
    brand: "even&odd",
    color: "black",
    category: "tute jumpsuit",
    price: 79,
  },
  {
    id: 23,
    img: p23_img,
    title: "Tuta jumpsuit",
    prevPrice: "79",
    newPrice: "59,99",
    brand: "pull&bear",
    color: "blue",
    category: "tute jumpsuit",
    price: 59,
  },
  {
    id: 24,
    img: p24_img,
    title: "JENNI",
    prevPrice: "65",
    newPrice: "49,99",
    brand: "altri marchi",
    color: "green",
    category: "tute jumpsuit",
    price: 49,
  },
  {
    id: 25,
    img: p25_img,
    title: "VESTE BOLERO",
    prevPrice: "75",
    newPrice: "54,99",
    brand: "altri marchi",
    color: "black",
    category: "intimo notte e loungewear",
    price: 54,
  },
  {
    id: 206,
    img: p206_img,
    title: "DEMI WIRED EXTROVERT",
    prevPrice: "120",
    newPrice: "105,99",
    brand: "altri marchi",
    color: "black",
    category: "intimo notte e loungewear",
    price: 105,
  },

  {
    id: 207,
    img: p207_img,
    title: "ENLIGHTENING",
    prevPrice: "120",
    newPrice: "89,99",
    brand: "altri marchi",
    color: "red",
    category: "intimo notte e loungewear",
    price: 89,
  },

  {
    id: 26,
    img: p26_img,
    title: "POLY PUFFER - Giacca invernale",
    prevPrice: "170",
    newPrice: "159,99",
    brand: "Jordan",
    color: "blue",
    category: "giacche",
    price: 159,
  },
  {
    id: 27,
    img: p27_img,
    title: "Nike Sportswear - Giacca invernale",
    prevPrice: "140",
    newPrice: "119,99",
    brand: "Nike",
    color: "grey",
    category: "giacche",
    price: 119,
  },

  {
    id: 28,
    img: p28_img,
    title: "GOSEI PUFFER JACKET",
    prevPrice: "130",
    newPrice: "99,99",
    brand: "The North Face",
    color: "violet",
    category: "giacche",
    price: 99,
  },
  {
    id: 29,
    img: p29_img,
    title: "PANT - Pantaloni cargo",
    prevPrice: "80",
    newPrice: "69,99",
    brand: "Nike",
    color: "black",
    category: "pantaloni",
    price: 69,
  },
  {
    id: 30,
    img: p30_img,
    title: "AIR PANT - Pantaloni sportivi",
    prevPrice: "75",
    newPrice: "65,99",
    brand: "Nike",
    color: "white",
    category: "pantaloni",
    price: 65,
  },
  {
    id: 31,
    img: p31_img,
    title: "RIPSTOP TAPER - Chino",
    prevPrice: "110",
    newPrice: "89,99",
    brand: "Calvin Klein",
    color: "black",
    category: "pantaloni",
    price: 89,
  },

  {
    id: 32,
    img: p32_img,
    title: "CLASSIC - Maglietta a manica lunga",
    prevPrice: "55",
    newPrice: "39,99",
    brand: "Vans",
    color: "black",
    category: "t-shirt e polo",
    price: 39,
  },
  {
    id: 33,
    img: p33_img,
    title: "AIR STRETCH - T-Shirt sport",
    prevPrice: "70",
    newPrice: "55,99",
    brand: "Jordan",
    color: "grey",
    category: "t-shirt e polo",
    price: 55,
  },
  {
    id: 34,
    img: p34_img,
    title: "CONNECTED LAYER",
    prevPrice: "80",
    newPrice: "64,99",
    brand: "Calvin Klein",
    color: "black",
    category: "t-shirt e polo",
    price: 64,
  },
  {
    id: 35,
    img: p35_img,
    title: "LANGARM BRAYDEN",
    prevPrice: "70",
    newPrice: "49,99",
    brand: "Altri marchi",
    color: "white",
    category: "camicie",
    price: 49,
  },
  {
    id: 36,
    img: p36_img,
    title: "CALVERT FLEX",
    prevPrice: "80",
    newPrice: "65,99",
    brand: "U.S. Polo",
    color: "black",
    category: "camicie",
    price: 65,
  },
  {
    id: 37,
    img: p37_img,
    title: "CALCUTA",
    prevPrice: "50",
    newPrice: "35,99",
    brand: "Mango",
    color: "violet",
    category: "camicie",
    price: 35,
  },
  {
    id: 38,
    img: p38_img,
    title: "FELPA BASIC MAXI LOGO",
    prevPrice: "65",
    newPrice: "47,99",
    brand: "EA7",
    color: "green",
    category: "maglie e felpe",
    price: 47,
  },
  {
    id: 39,
    img: p39_img,
    title: "AIR CREW",
    prevPrice: "80",
    newPrice: "63,99",
    brand: "Nike",
    color: "grey",
    category: "maglie e felpe",
    price: 63,
  },
  {
    id: 40,
    img: p40_img,
    title: "MONOLOGO CREW NECK",
    prevPrice: "90",
    newPrice: "72,99",
    brand: "Calvin Klein",
    color: "blue",
    category: "maglie e felpe",
    price: 72,
  },
  {
    id: 41,
    img: p41_img,
    title: "Jeans baggy",
    prevPrice: "110",
    newPrice: "102,99",
    brand: "Levi's",
    color: "blue",
    category: "jeans",
    price: 102,
  },
  {
    id: 42,
    img: p42_img,
    title: "Jeans baggy",
    prevPrice: "104",
    newPrice: "87,99",
    brand: "Levi's",
    color: "blue",
    category: "jeans",
    price: 87,
  },
  {
    id: 43,
    img: p43_img,
    title: "501® ORIGINAL",
    prevPrice: "89",
    newPrice: "74,99",
    brand: "Levi's",
    color: "blue",
    category: "jeans",
    price: 74,
  },
  {
    id: 44,
    img: p44_img,
    title: "CARSTEN - Pantaloni sportivi",
    prevPrice: "49",
    newPrice: "33,99",
    brand: "U.S. Polo",
    color: "blue",
    category: "bermuda",
    price: 33,
  },
  {
    id: 45,
    img: p45_img,
    title: "GRAPHIC - Shorts",
    prevPrice: "40",
    newPrice: "22,99",
    brand: "Altri marchi",
    color: "grey",
    category: "bermuda",
    price: 22,
  },
  {
    id: 46,
    img: p46_img,
    title: "BOSTON SWINGMAN SHORT",
    prevPrice: "60",
    newPrice: "49,99",
    brand: "Nike",
    color: "green",
    category: "bermuda",
    price: 49,
  },
  {
    id: 47,
    img: p47_img,
    title: "NBA LEBRON JAMES",
    prevPrice: "65",
    newPrice: "43,99",
    brand: "Jordan",
    color: "violet",
    category: "abbigliamento sportivo",
    price: 43,
  },
  {
    id: 48,
    img: p48_img,
    title: "NEW YORK YANKEES",
    prevPrice: "90",
    newPrice: "72,99",
    brand: "Altri marchi",
    color: "white",
    category: "abbigliamento sportivo",
    price: 72,
  },
  {
    id: 49,
    img: p49_img,
    title: "ALFONSA HOODY",
    prevPrice: "100",
    newPrice: "85,99",
    brand: "Altri marchi",
    color: "green",
    category: "abbigliamento sportivo",
    price: 85,
  },
  {
    id: 50,
    img: p50_img,
    title: "Swimwear",
    prevPrice: "50",
    newPrice: "34,99",
    brand: "Altri marchi",
    color: "black",
    category: "intimo",
    price: 34,
  },
  {
    id: 501,
    img: p501_img,
    title: "Calzamaglia",
    prevPrice: "30",
    newPrice: "21,99",
    brand: "Altri marchi",
    color: "black",
    category: "intimo",
    price: 21,
  },
  {
    id: 502,
    img: p502_img,
    title: "Accappatoio",
    prevPrice: "45",
    newPrice: "33,99",
    brand: "Altri marchi",
    color: "grey",
    category: "intimo",
    price: 33,
  },
];

export default all;
