import p50_img from '../../assets/img-scarpe/product_50.png';
import p51_img from '../../assets/img-scarpe/product_51.png';
import p52_img from '../../assets/img-scarpe/product_52.png';
import p53_img from '../../assets/img-scarpe/product_53.png';
import p54_img from '../../assets/img-scarpe/product_54.png';
import p55_img from '../../assets/img-scarpe/product_55.png';
import p56_img from '../../assets/img-scarpe/product_56.png';
import p57_img from '../../assets/img-scarpe/product_57.png';
import p58_img from '../../assets/img-scarpe/product_58.png';
import p59_img from '../../assets/img-scarpe/product_59.png';
import p60_img from '../../assets/img-scarpe/product_60.png';
import p61_img from '../../assets/img-scarpe/product_61.png';
import p62_img from '../../assets/img-scarpe/product_62.png';
import p63_img from '../../assets/img-scarpe/product_63.png';
import p64_img from '../../assets/img-scarpe/product_64.png';
import p65_img from '../../assets/img-scarpe/product_65.png';
import p66_img from '../../assets/img-scarpe/product_66.png';
import p67_img from '../../assets/img-scarpe/product_67.png';
import p68_img from '../../assets/img-scarpe/product_68.png';
import p69_img from '../../assets/img-scarpe/product_69.png';
import p70_img from '../../assets/img-scarpe/product_70.png';
import p71_img from '../../assets/img-scarpe/product_71.png';
import p72_img from '../../assets/img-scarpe/product_72.png';
import p73_img from '../../assets/img-scarpe/product_73.png';
import p74_img from '../../assets/img-scarpe/product_74.png';
import p75_img from '../../assets/img-scarpe/product_75.png';
import p76_img from '../../assets/img-scarpe/product_76.png';
import p77_img from '../../assets/img-scarpe/product_77.png';
import p78_img from '../../assets/img-scarpe/product_78.png';
import p79_img from '../../assets/img-scarpe/product_79.png';
import p80_img from '../../assets/img-scarpe/product_80.png';
import p81_img from '../../assets/img-scarpe/product_81.png';
import p82_img from '../../assets/img-scarpe/product_82.png';
import p83_img from '../../assets/img-scarpe/product_83.png';
import p84_img from '../../assets/img-scarpe/product_84.png';
import p85_img from '../../assets/img-scarpe/product_85.png';
import p86_img from '../../assets/img-scarpe/product_86.png';
import p87_img from '../../assets/img-scarpe/product_87.png';
import p88_img from '../../assets/img-scarpe/product_88.png';
import p89_img from '../../assets/img-scarpe/product_89.png';
import p90_img from '../../assets/img-scarpe/product_90.png';
import p91_img from '../../assets/img-scarpe/product_91.png';




const data = [
  {
    id: 50,
    img: p50_img,
    title: "SCARPE",
    prevPrice: "€120",
    newPrice: "99.99",
    brand: "Nike",
    color: "white",
    category: "lifestyle",
    gender: "uomo",
    price: 99.99,
  },
  {
    id: 51,
    img: p51_img,
    title: "Nike Air Vapormax Plus",
    prevPrice: "€100",
    newPrice: "88.99",
    brand: "Nike",
    color: "white",
    category: "lifestyle",
    gender: "uomo",
    price: 88.99,
  },

  {
    id: 52,
    img: p52_img,
    title: "Nike Waffle One Sneaker",
    prevPrice: "€110",
    newPrice: "95.99",
    brand: "Nike",
    color: "green",
    category: "lifestyle",
    gender: "uomo",
    price: 95.99,
  },
  {
    id: 53,
    img: p53_img,
    title: "Nike Running Shoe",
    prevPrice: "€130",
    newPrice: "110.99",
    brand: "Adidas",
    color: "black",
    category: "lifestyle",
    gender: "uomo",
    price: 110.99,
  },
  {
    id: 54,
    img: p54_img,
    title: "Flat Slip On Pumps",
    prevPrice: "€140",
    newPrice: "120.99",
    brand: "Vans",
    color: "green",
    category: "tennis",
    gender: "uomo",
    price: 120.99,
  },
  {
    id: 55,
    img: p55_img,
    title: "Knit Ballet Flat",
    prevPrice: "€150",
    newPrice: "130,99",
    brand: "Adidas",
    color: "black",
    category: "tennis",
    gender: "uomo",
    price: 130.99,
  },
  {
    id: 56,
    img: p56_img,
    title: "Flat Slip On Pumps",
    prevPrice: "165",
    newPrice: "150.99",
    brand: "Vans",
    color: "green",
    category: "tennis",
    gender: "uomo",
    price: 150.99,
    
  },
  {
    id: 57,
    img: p57_img,
    title: "Knit Ballet Flat",
    prevPrice: "140",
    newPrice: "115,99",
    brand: "Adidas",
    color: "black",
    category: "tennis",
    gender: "uomo",
    price: 115.99,
    
  },
  {
    id: 58,
    img: p58_img,
    title: "Flat Slip On Pumps",
    prevPrice: "130",
    newPrice: "105.99",
    brand: "Vans",
    color: "green",
    category: "running",
    gender: "uomo",
    price: 105.99,
  },
  {
    id: 59,
    img: p59_img,
    title: "Knit Ballet Flat",
    prevPrice: "180",
    newPrice: "160,99",
    brand: "Adidas",
    color: "black",
    category: "running",
    gender: "uomo",
    price: 160.99,
  },
  {
    id: 60,
    img: p60_img,
    title: "Flat Slip On Pumps",
    prevPrice: "130",
    newPrice: "109.99",
    brand: "Vans",
    color: "green",
    category: "running",
    gender: "uomo",
    price: 109.99,
  },
  {
    id: 61,
    img: p61_img,
    title: "Knit Ballet Flat",
    prevPrice: "220",
    newPrice: "199,99",
    brand: "Adidas",
    color: "black",
    category: "running",
    gender: "uomo",
    price: 199.99,
  },
  {
    id: 62,
    img: p62_img,
    title: "Flat Slip On Pumps",
    prevPrice: "200",
    newPrice: "180.99",
    brand: "Vans",
    color: "green",
    category: "calcio",
    gender: "uomo",
    price: 180.99,
  },
  {
    id: 63,
    img: p63_img,
    title: "Knit Ballet Flat",
    prevPrice: "179",
    newPrice: "149,99",
    brand: "Adidas",
    color: "black",
    category: "calcio",
    gender: "uomo",
    price: 149.99,
  },
  {
    id: 64,
    img: p64_img,
    title: "Flat Slip On Pumps",
    prevPrice: "€100",
    newPrice: "99.99",
    brand: "Vans",
    color: "green",
    category: "calcio",
    gender: "uomo",
    price: 99.99,
  },
  {
    id: 65,
    img: p65_img,
    title: "Knit Ballet Flat",
    prevPrice: "140",
    newPrice: "132,99",
    brand: "Adidas",
    color: "black",
    category: "calcio",
    gender: "uomo",
    price: 132.99,
  },
  {
    id: 66,
    img: p66_img,
    title: "Knit Ballet Flat",
    prevPrice: "150",
    newPrice: "109,99",
    brand: "Adidas",
    color: "black",
    category: "lifestyle",
    gender: "donna",
    price: 109.99,
  },
  {
    id: 67,
    img: p67_img,
    title: "Knit Ballet Flat",
    prevPrice: "210",
    newPrice: "189,99",
    brand: "Adidas",
    color: "black",
    category: "lifestyle",
    gender: "donna",
    price: 189.99,
  },
  {
    id: 68,
    img: p68_img,
    title: "Knit Ballet Flat",
    prevPrice: "170",
    newPrice: "149,99",
    brand: "Adidas",
    color: "black",
    category: "lifestyle",
    gender: "donna",
    price: 149.99,
  },
  {
    id: 69,
    img: p69_img,
    title: "Knit Ballet Flat",
    prevPrice: "230",
    newPrice: "209,99",
    brand: "Adidas",
    color: "black",
    category: "lifestyle",
    gender: "donna",
    price: 209.99,
  },
  {
    id: 70,
    img: p70_img,
    title: "Knit Ballet Flat",
    prevPrice: "180",
    newPrice: "169,99",
    brand: "Adidas",
    color: "black",
    category: "tennis",
    gender: "donna",
    price: 169.99,
  },
  {
    id: 71,
    img: p71_img,
    title: "Knit Ballet Flat",
    prevPrice: "€180",
    newPrice: "169,99",
    brand: "Adidas",
    color: "black",
    category: "tennis",
    gender: "donna",
    price: 169.99,
  },
  {
    id: 72,
    img: p72_img,
    title: "Knit Ballet Flat",
    prevPrice: "€250",
    newPrice: "209,99",
    brand: "Adidas",
    color: "black",
    category: "tennis",
    gender: "donna",
    price: 209.99,
  },
  {
    id: 73,
    img: p73_img,
    title: "Knit Ballet Flat",
    prevPrice: "€130",
    newPrice: "99,99",
    brand: "Adidas",
    color: "black",
    category: "tennis",
    gender: "donna",
    price: 99.99,
  },
  {
    id: 74,
    img: p74_img,
    title: "Knit Ballet Flat",
    prevPrice: "€100",
    newPrice: "84,99",
    brand: "Adidas",
    color: "black",
    category: "running",
    gender: "donna",
    price: 84.99,
  },
  {
    id: 75,
    img: p75_img,
    title: "Knit Ballet Flat",
    prevPrice: "89",
    newPrice: "75,99",
    brand: "Adidas",
    color: "black",
    category: "running",
    gender: "donna",
    price: 75.99,
  },
  {
    id: 76,
    img: p76_img,
    title: "Knit Ballet Flat",
    prevPrice: "90",
    newPrice: "73,99",
    brand: "Adidas",
    color: "black",
    category: "running",
    gender: "donna",
    price: 73.99,
  },
  {
    id: 77,
    img: p77_img,
    title: "Knit Ballet Flat",
    prevPrice: "€100",
    newPrice: "80,99",
    brand: "Adidas",
    color: "black",
    category: "running",
    gender: "donna",
    price: 80.99,
  },
  {
    id: 78,
    img: p78_img,
    title: "Knit Ballet Flat",
    prevPrice: "190",
    newPrice: "159,99",
    brand: "Adidas",
    color: "black",
    category: "calcio",
    gender: "donna",
    price: 159.99,
  },
  {
    id: 79,
    img: p79_img,
    title: "Knit Ballet Flat",
    prevPrice: "€200",
    newPrice: "179,99",
    brand: "Adidas",
    color: "black",
    category: "calcio",
    gender: "donna",
    price: 179.99,
  },
  {
    id: 80,
    img: p80_img,
    title: "Knit Ballet Flat",
    prevPrice: "220",
    newPrice: "189,99",
    brand: "Adidas",
    color: "black",
    category: "calcio",
    gender: "donna",
    price: 189.99,
  },
  {
    id: 81,
    img: p81_img,
    title: "Knit Ballet Flat",
    prevPrice: "200",
    newPrice: "149,99",
    brand: "Adidas",
    color: "black",
    category: "calcio",
    gender: "donna",
    price: 149.99,
  },
  {
    id: 82,
    img: p82_img,
    title: "Knit Ballet Flat",
    prevPrice: "€70",
    newPrice: "49,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 49.99,
  },
  {
    id: 83,
    img: p83_img,
    title: "Knit Ballet Flat",
    prevPrice: "€70",
    newPrice: "49,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 49.99,
  },
  {
    id: 84,
    img: p84_img,
    title: "Knit Ballet Flat",
    prevPrice: "€80",
    newPrice: "42,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 42.99,
  },
  {
    id: 85,
    img: p85_img,
    title: "Knit Ballet Flat",
    prevPrice: "€100",
    newPrice: "85,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 85.99,
    
  },
  {
    id: 86,
    img: p86_img,
    title: "Knit Ballet Flat",
    prevPrice: "€100",
    newPrice: "70,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 70.99,
  },
  {
    id: 87,
    img: p87_img,
    title: "Knit Ballet Flat",
    prevPrice: "55",
    newPrice: "42,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 42,
  },
  {
    id: 88,
    img: p88_img,
    title: "Knit Ballet Flat",
    prevPrice: "€80",
    newPrice: "55,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 55.99,
  },
  {
    id: 89,
    img: p89_img,
    title: "Knit Ballet Flat",
    prevPrice: "77",
    newPrice: "63,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 63.99,
  },
  {
    id: 90,
    img: p90_img,
    title: "Knit Ballet Flat",
    prevPrice: "89",
    newPrice: "63,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 63.99,
  },
  {
    id: 91,
    img: p91_img,
    title: "Knit Ballet Flat",
    prevPrice: "89",
    newPrice: "61,99",
    brand: "Adidas",
    color: "black",
    gender: "bambini",
    price: 61.99,
  },

];

export default data;
